FROM mysql
ENV MYSQL_ROOT_USER=root \
    MYSQL_ROOT_PASSWORD=rootpassword \
    MYSQL_DATABASE=guacamole_db \
    MYSQL_USER=guacamole_user \
    MYSQL_PASSWORD=guacamolepassword
COPY ./initdb.sql /
RUN mysql -u guacamole_user -pguacamolepassword guacamole_db < /initdb.sql