version: "3.8"

volumes:
  guacamolemysql:
    external: true

networks:
  guacamole:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    enable_ipv6: false

services:
  db:
    image: mysql
    volumes:
      - "guacamolemysql:/var/lib/mysql"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: rootpassword
        MYSQL_DATABASE: guacamole_db
        MYSQL_USER: guacamole_user
        MYSQL_PASSWORD: guacamolepassword
    container_name: guacamole_db
    networks:
      guacamole:
    hostname: guacamole_db

  server:
    image: guacamole/guacd
    volumes:
      - .:/tmp
    container_name: guacd
    networks:
      guacamole:
    ports:
    - '4822:4822'


  client:
    image: guacamole/guacamole
    ports:
    - '8080:8080'
    networks:
      guacamole:
    links:
      - server:guacd
      - db:guacamole_db
    depends_on:
      - server
      - db
    container_name: guacamole
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamolepassword
      GUACD_HOSTNAME: server
      MYSQL_HOSTNAME: db
    expose:
      - '8080'

  player:
    networks:
      guacamole:
    build:
      context: ./glyptodon-enterprise-player
      dockerfile: Dockerfile
    image: session_player
    ports:
    - '8081:80'
    container_name: session_player
    hostname: session_player
    expose:
      - '8081'
    depends_on:
      - server
  
  guac_custom_client:
    networks:
      guacamole:
    build:
      context: ./guac-vue
      dockerfile: Dockerfile
    image: guac_custom_client
    ports:
    - '8083:8080'
    container_name: guac_custom_client
    hostname: guac_custom_client
    expose:
      - '8080'
    links: 
      - guac_custom_proxy
    depends_on: 
      - guac_custom_proxy
  
  guac_custom_proxy:
    networks:
      guacamole:
    build:
      context: ./guac
      dockerfile: Dockerfile
    image: guac_custom_proxy
    ports:
    - '4567:4567'
    container_name: guac_custom_proxy
    hostname: guac_custom_proxy
    expose:
      - '4567'
    links: 
      - server
    depends_on: 
      - server
